### PR TITLE
Fix checkAmbientMode being called inconsistently on initial page load

### LINKED ISSUE #1: Just not working
Just not working. Firefox 109.0

### PR DESCRIPTION
**Pull request by cvaugh**
This should resolve #1 and #2.

### CODE REVIEW

**Comment by smolpaw** [comment]
Should be resolved with the new version

**Comment by cvaugh** [comment]
This still appears to be happening. The new version re-enables ambient mode if it has been manually turned off.

**Comment by smolpaw** [comment]
What are the logs you are getting in browser console ?
The script can currently print one of these 4 logs

1. Ambient mode is ON
2. Ambient mode is OFF
3. Player options not found
4. Failed to turn off ambient mode. Max attempts reached.

**Comment by cvaugh** [comment]
> Ambient mode is OFF

I reinstalled the addon and it seems to be working as expected now.

**Pull request closed without merging**
